# Use root/example as user/password credentials

##sudo docker exec -it mysqlp21 mysql -u root -pprojetoes


version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysqlp21
    environment:
      MYSQL_DATABASE: esp21_db
      MYSQL_ROOT_PASSWORD: comoassim
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "esp21_joints"
      KAFKA_CREATE_TOPICS: "esp21_alarms"


